# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (runs every 6 hours)
  schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run workflow manually from the Actions tab
  workflow_dispatch:
  # Run on push to main branch
  push: {branches: ["main", "master"]} # Ditambahkan master untuk kompatibilitas
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest # <-- INI BAGIAN YANG DIPERBAIKI
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: santaimany
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta # Ganti sesuai zona waktu Anda
          config_display: large
          
          # Plugins
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_threshold: 0%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base-header, follow-up, general-stats
